### PR TITLE
remove leading and trailing whitespace of form values on blur

### LINKED ISSUE #49: Trim the values in the intputs instead of reporting an error
As suggestion, we usually copy and paste URLs from other links that sometimes can introduce blank spaces at the beginning, instead of reporting them as an error describing that the URL has not the correct format, trim the value and automatically remove the blank spaces at the beginning and at the end

### PR DESCRIPTION
**Pull request by xjusko**
resolves #49

### CODE REVIEW

**Review by khermano — COMMENTED** [review]
We should also check and trim it in the backend to provide consistency and avoid possible issues with automated builds in the future. What do you think?

**Comment by petrberan** [comment]
Valid point @khermano , which opens the Pandora box, as we don't have the same checks from FE on BE, and we should.

**Review by petrberan — CHANGES_REQUESTED** [review]
See above

**Comment by xjusko** [comment]
@petrberan @khermano I've added basic string trimming on BE, but will refactor it later when implementing full validation on BE in #56

**Comment by xjusko** [comment]
Sure, I removed the trimming on BE and will include it in #56

**Review by khermano — APPROVED** [review]
Looks good, thank you @xjusko :)

**Review by petrberan — APPROVED** [review]
LGTM

**Pull request merged**
